### ISSUE TITLE
Using timestamps() raises exception

### ISSUE THREAD

**Issue by kodburn** [kobil-systems/mongodb_ecto#124]
Hi, whenever I use timestamps() in my schema, I get this exception when inserting to db:
```
** (ArgumentError) Invalid expression for MongoDB adapter in insert command
    (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:464: Mongo.Ecto.NormalizedQuery.error/1
    (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:274: Mongo.Ecto.NormalizedQuery.command/4
    (mongodb_ecto) lib/mongo_ecto/normalized_query.ex:124: Mongo.Ecto.NormalizedQuery.insert/3
    (mongodb_ecto) lib/mongo_ecto.ex:520: Mongo.Ecto.insert/6
            (ecto) lib/ecto/repo/schema.ex:297: Ecto.Repo.Schema.apply/5
            (ecto) lib/ecto/repo/schema.ex:81: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
```
It doesn't matter if I `Repo.insert` schema or changeset.
My schema:

```
  @primary_key {:id, :binary_id, autogenerate: true}
  schema "game_versions" do
    field :name
    field :game_id
    field :game_name
    field :engine_version
    field :engine_type
    timestamps()
  end
```

As soon as I delete `timestamps()` the error disappears. I tried different things, none of them worked.
I thought that `field :created_at, Ecto.DateTime, default: Ecto.DateTime.utc` can be a solution, but as I found out later, default fields are set once.
   Any ideas?

**Comment by ankhers** [comment]
Would you be able to list your dependencies and versions?

**Comment by kodburn** [comment]
Sure.
`  defp deps do
    [
      {:ecto, "~> 1.1", override: true},
      {:mongodb_ecto, "~> 0.1.5"},
      {:emq, git: "git@source.niemau.de:casino/emq.git"},
      {:emq2, git: "git@source.niemau.de:experiments/emq2.git"},
      {:amqp, "~> 0.2.1", override: true},
      {:rabbit_common, "~> 3.6.9", override: true},
      {:ex_machina, "~> 2.0", only: :test}
    ]
  end
`

**Comment by michalmuskala** [comment]
Could you also show the exact code that's causing the error?

Also - for the future, please use three backticks to mark code blocks. It makes it so much easier to read (I amended your posts to use it).

**Comment by kodburn** [comment]
So the error appears when I either try to insert using only schema:
`Repo.insert(%GameVersion{})`
or changeset:
`Repo.insert(GameVersion.changeset(%GameVersion{}, %{}))`

**Comment by kodburn** [comment]
The error persists in my other schemas too. Although, I can create a datetime field wothout any errors.

**Comment by ankhers** [comment]
Is this still happening on the `ecto-2` or `ecto-2.1` branch?
